name: PR Approval Check

on:
  pull_request_review:
    types:
      - submitted

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      needs_check: ${{ steps.filter.outputs.needs_check }}
      modified_files: ${{ steps.filter.outputs.needs_check_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if approval check is needed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            needs_check:
              - "bin/**"
  approval-check:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.needs_check == 'true'
    permissions:
      pull-requests: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.12"
          cache: "pipenv"

      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install

      - name: Install dependencies
        run: pip install requests

      - name: Run approval check
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_LEV_ADMIN_GITHUB_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: pipenv run python3 -m bin.check_pr_approvals '${{ needs.detect-changes.outputs.modified_files }}'