name: ðŸ“ˆ Generate Tagging Coverage Report

on:
  workflow_dispatch:
    inputs:
      billing_period:
        description: "Billing period in format YYYY-MM (e.g., 2025-01)"
        required: true
        type: string
      business_unit:
        description: "Select a business unit"
        required: true
        type: choice
        options:
          - HMPPS
          - Platforms
          - LAA
          - Central Digital
          - Technology Services
          - OPG
          - HMCTS
          - YJB
          - CICA

permissions:
  id-token: write
  contents: write

jobs:
  generate-tagging-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@f487a3d99423b03b33cbe8a0944867cb0f4223f9 # v4.0.2
        with:
          role-to-assume: ${{secrets.AWS_COAT_GITHUB_ACTIONS_ROLE_ARN}}
          aws-region: eu-west-2
      - name: Run Python script
        run: |
            pipenv run python3 -m bin.tagging_coverage_report \
            --billing_period "${{ github.event.inputs.billing_period }}" \
            --business_unit "${{ github.event.inputs.business_unit }}"
        env:
          GH_TOKEN: ${{ secrets.ENTERPRISE_BILLING_TOKEN_FROM_TONY }}
          ADMIN_SLACK_TOKEN: ${{ secrets.ADMIN_SLACK_TOKEN }}
      - name: Report failure to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@f6eea643ddcd831f1a3c4d518aefd6098ef680e6 # 2.5.0
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Failed to run Generate Tagging Coverage Report job"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
